services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DB_NAME=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
      - ./dataset:/docker-entrypoint-initdb.d
  python-job:
    image: manojmanivannan18/postgres-playground-py:latest
    depends_on:
      - db
volumes:
  db:
    driver: local
